apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: project-request-template
  namespace: servicenow
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
      openshift.io/node-selector: appworker=true
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    creationTimestamp: null
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: edit
    namespace: ${PROJECT_NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ${PROJECT_REQUESTING_USER}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admin
    namespace: ${PROJECT_NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ocpadmin
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: ${PROJECT_NAME}-limits
    namespace: ${PROJECT_NAME}
  spec:
    limits:
    - max:
        cpu: "2"
        memory: 12Gi
      type: Pod
    - default:
        cpu: 200m
        memory: 600Mi
      defaultRequest:
        cpu: 100m
        memory: 500Mi
      max:
        cpu: "2"
        memory: 12Gi
      min:
        cpu: 100m
        memory: 4Mi
      type: Container
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: ${PROJECT_NAME}-quota
    namespace: ${PROJECT_NAME}
  spec:
    hard:
      limits.cpu: ${PROJECT_CPU}
      limits.memory: ${PROJECT_MEMORY}
      persistentvolumeclaims: "5"
      pods: "20"
      requests.storage: ${PROJECT_STORAGE}
parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_REQUESTING_USER
- name: PROJECT_CPU
- name: PROJECT_MEMORY
- name: PROJECT_STORAGE
