apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: template-instance-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: servicenow-view-create
subjects:
- kind: ServiceAccount
  name: template-instance-controller
  namespace: openshift-infra

